---
- hosts: backends
  tasks:
   - name: Start backends
     shell: pkill java; cd hillview; nohup java -jar hillview-server-jar-with-dependencies.jar 0.0.0.0:3569 &

- hosts: web
  tasks:
   - name: Start web server
     shell: pkill java; WEB_CLUSTER_DESCRIPTOR="serverlist" nohup apache-tomcat-8.5.8/bin/startup.sh
